# Generated by Django 5.1.3 on 2024-11-16 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0005_genre_film_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="film",
            name="genre",
        ),
        migrations.AddField(
            model_name="film",
            name="genre",
            field=models.ManyToManyField(
                default="", related_name="Films", to="Project.genre"
            ),
        ),
    ]
