# Generated by Django 5.1.3 on 2024-11-18 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Project", "0010_favorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Poster",
        ),
    ]
